[project]
name = "mddoc"
version = "0.3.3"
description = "Markdown-Dokumentationstool"
requires-python = ">=3.13"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"