# Generated by Django 5.2.3 on 2025-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='tokens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
