# Generated by Django 5.2.3 on 2025-06-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_documentation_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='tokens',
        ),
    ]
