# Generated by Django 5.2.3 on 2025-06-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_documentation_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='tag',
            field=models.TextField(blank=True, default=''),
        ),
    ]
