# Generated by Django 5.2.3 on 2025-06-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_alter_documentation_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='tag',
            field=models.TextField(blank=True, db_default='-', default='-'),
        ),
    ]
