# Generated by Django 5.2.3 on 2025-06-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_documentation_is_archived_documentation_is_markdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='uri',
            field=models.CharField(blank=True, help_text='If a URI is labelled, then the resource is regarded as meta information for the resource referenced with the URI.', max_length=2000, null=True, verbose_name='URI'),
        ),
    ]
