# Generated by Django 5.2.3 on 2025-06-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_alter_documentation_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
