# Generated by Django 5.2.3 on 2025-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0010_alter_documentation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
