# Generated by Django 5.2.3 on 2025-06-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0012_remove_documentation_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='warning',
        ),
    ]
