# Generated by Django 5.2.3 on 2025-06-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0013_remove_documentation_warning'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentation',
            new_name='Doc',
        ),
    ]
