# Generated by Django 5.2.3 on 2025-06-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0014_rename_documentation_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The time specification is used to associate emails, logs or results data with the time of receipt, collection or implementation. The search results can be narrowed down in terms of time.', null=True, verbose_name='Associated point in time'),
        ),
    ]
