# Generated by Django 5.2.3 on 2025-06-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0015_doc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='For emails, logs or results data with the time associated.', null=True, verbose_name='Associated point in time'),
        ),
    ]
