# Generated by Django 5.2.3 on 2025-06-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0016_alter_doc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='If checked, the document is initially excluded in the search view.', verbose_name='Is considered archived or stale'),
        ),
    ]
