# Generated by Django 5.2.3 on 2025-06-23 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0018_alter_doc_description_alter_doc_is_markdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
