# Generated by Django 5.2.3 on 2025-06-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0019_doc_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, the document is initially excluded in the search view.', verbose_name='Is considered archived or stale'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
