# Generated by Django 5.2.3 on 2025-06-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0020_alter_doc_created_at_alter_doc_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
    ]
