# Generated by Django 5.2.3 on 2025-06-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0024_alter_doc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='Log'),
        ),
    ]
