# Generated by Django 5.2.3 on 2025-06-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0025_doc_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Is flagged'),
        ),
    ]
