# Generated by Django 5.2.3 on 2025-06-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0026_doc_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is flagged'),
        ),
    ]
