# Generated by Django 5.2.3 on 2025-06-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0028_timerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
    ]
