# Generated by Django 5.2.3 on 2025-06-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0029_alter_timerecord_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='last_settlement',
            field=models.DateField(blank=True, db_index=True, help_text='Date of the last settlement of outstanding hours', null=True, verbose_name='Last settlement'),
        ),
    ]
