# Generated by Django 5.2.3 on 2025-06-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0030_doc_last_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='has_unsettled_tr',
            field=models.BooleanField(default=False, verbose_name='Has unsettled time records'),
        ),
    ]
