# Generated by Django 5.2.3 on 2025-07-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0031_doc_has_unsettled_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='settled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
