# Generated by Django 5.2.3 on 2025-07-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0032_timerecord_settled_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'permissions': [('search', 'Can search documents')]},
        ),
    ]
