# Generated by Django 5.2.3 on 2025-07-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0034_timerecord_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'permissions': [('search', 'Can search documents'), ('add_time_record', 'Can add time records'), ('time_analyse', 'Can analyse time records'), ('extract', 'Can extract text from uri of documents'), ('restore', 'Can restore deleted documents'), ('edit', 'Can edit documents'), ('add_log', 'Can add logs to documents'), ('flag', 'Can flag documents'), ('view', 'Can view documents')]},
        ),
    ]
