# Generated by Django 5.2.4 on 2025-07-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0036_checklistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='checked_at',
        ),
    ]
