# Generated by Django 5.2.4 on 2025-07-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0037_remove_checklistitem_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='checked',
            field=models.BooleanField(blank=True, db_default=False, default=False),
        ),
    ]
