# Generated by Django 5.2.4 on 2025-07-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0038_checklistitem_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Filename')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='doc/%Y/%m', verbose_name='File')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='docs', to='doc.file', verbose_name='Linked files'),
        ),
    ]
