# Generated by Django 5.2.4 on 2025-07-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0041_auto_20250715_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='file',
        ),
        migrations.AlterField(
            model_name='doc',
            name='time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='For emails, logs or results data.', null=True, verbose_name='Assoc. point in time'),
        ),
    ]
