# Generated by Django 5.2.4 on 2025-07-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0042_remove_doc_file_alter_doc_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='reactivation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reactivation time'),
        ),
    ]
