# Generated by Django 5.2.4 on 2025-07-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0043_doc_reactivation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
    ]
