# Generated by Django 5.2.4 on 2025-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0044_doc_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='tag',
            field=models.TextField(blank=True, help_text='Holds the string representation of the tags.', null=True),
        ),
    ]
