# Generated by Django 5.2.4 on 2025-07-24 03:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0046_file_is_volatile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
