# Generated by Django 5.2.4 on 2025-07-24 03:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0048_auto_20250724_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
