# Generated by Django 5.2.4 on 2025-07-24 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0049_auto_20250724_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
