# Generated by Django 5.2.4 on 2025-07-24 03:45

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("doc", "File")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ('doc', '0050_file_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
